const SwordShield = [
    { name: 'Grookey', displayNumber: '001', dexNumber: '810' },
    { name: 'Thwackey', displayNumber: '002', dexNumber: '811' },
    { name: 'Rillaboom', displayNumber: '003', dexNumber: '812' },
    { name: 'Scorbunny', displayNumber: '004', dexNumber: '813' },
    { name: 'Raboot', displayNumber: '005', dexNumber: '814' },
    { name: 'Cinderace', displayNumber: '006', dexNumber: '815' },
    { name: 'Sobble', displayNumber: '007', dexNumber: '816' },
    { name: 'Drizzile', displayNumber: '008', dexNumber: '817' },
    { name: 'Inteleon', displayNumber: '009', dexNumber: '818' },
    { name: 'Skwovet', displayNumber: '010', dexNumber: '819' },
    { name: 'Greedent', displayNumber: '011', dexNumber: '820' },
    { name: 'Rookidee', displayNumber: '012', dexNumber: '821' },
    { name: 'Corvisquire', displayNumber: '013', dexNumber: '822' },
    { name: 'Corviknight', displayNumber: '014', dexNumber: '823' },
    { name: 'Blipbug', displayNumber: '015', dexNumber: '824' },
    { name: 'Dottler', displayNumber: '016', dexNumber: '825' },
    { name: 'Orbeetle', displayNumber: '017', dexNumber: '826' },
    { name: 'Nickit', displayNumber: '018', dexNumber: '827' },
    { name: 'Thievul', displayNumber: '019', dexNumber: '828' },
    { name: 'Gossifleur', displayNumber: '020', dexNumber: '829' },
    { name: 'Eldegoss', displayNumber: '021', dexNumber: '830' },
    { name: 'Wooloo', displayNumber: '022', dexNumber: '831' },
    { name: 'Dubwool', displayNumber: '023', dexNumber: '832' },
    { name: 'Chewtle', displayNumber: '024', dexNumber: '833' },
    { name: 'Drednaw', displayNumber: '025', dexNumber: '834' },
    { name: 'Yamper', displayNumber: '026', dexNumber: '835' },
    { name: 'Boltund', displayNumber: '027', dexNumber: '836' },
    { name: 'Rolycoly', displayNumber: '028', dexNumber: '837' },
    { name: 'Carkol', displayNumber: '029', dexNumber: '838' },
    { name: 'Coalossal', displayNumber: '030', dexNumber: '839' },
    { name: 'Applin', displayNumber: '031', dexNumber: '840' },
    { name: 'Flapple', displayNumber: '032', dexNumber: '841' },
    { name: 'Appletun', displayNumber: '033', dexNumber: '842' },
    { name: 'Silicobra', displayNumber: '034', dexNumber: '843' },
    { name: 'Sandaconda', displayNumber: '035', dexNumber: '844' },
    { name: 'Cramorant', displayNumber: '036', dexNumber: '845' },
    { name: 'Arrokuda', displayNumber: '037', dexNumber: '846' },
    { name: 'Barraskewda', displayNumber: '038', dexNumber: '847' },
    { name: 'Toxel', displayNumber: '039', dexNumber: '848' },
    { name: 'Toxtricity', displayNumber: '040', dexNumber: '849' },
    { name: 'Sizzlipede', displayNumber: '041', dexNumber: '850' },
    { name: 'Centiskorch', displayNumber: '042', dexNumber: '851' },
    { name: 'Clobbopus', displayNumber: '043', dexNumber: '852' },
    { name: 'Grapploct', displayNumber: '044', dexNumber: '853' },
    { name: 'Sinistea', displayNumber: '045', dexNumber: '854' },
    { name: 'Polteageist', displayNumber: '046', dexNumber: '855' },
    { name: 'Hatenna', displayNumber: '047', dexNumber: '856' },
    { name: 'Hattrem', displayNumber: '048', dexNumber: '857' },
    { name: 'Hatterene', displayNumber: '049', dexNumber: '858' },
    { name: 'Impidimp', displayNumber: '050', dexNumber: '859' },
    { name: 'Morgrem', displayNumber: '051', dexNumber: '860' },
    { name: 'Grimmsnarl', displayNumber: '052', dexNumber: '861' },
    { name: 'Obstagoon', displayNumber: '053', dexNumber: '862' },
    { name: 'Perrserker', displayNumber: '054', dexNumber: '863' },
    { name: 'Cursola', displayNumber: '055', dexNumber: '864' },
    { name: 'Sirfetch’d', displayNumber: '056', dexNumber: '865' },
    { name: 'Mr. Rime', displayNumber: '057', dexNumber: '866' },
    { name: 'Runerigus', displayNumber: '058', dexNumber: '867' },
    { name: 'Milcery', displayNumber: '059', dexNumber: '868' },
    { name: 'Alcremie', displayNumber: '060', dexNumber: '869' },
    { name: 'Falinks', displayNumber: '061', dexNumber: '870' },
    { name: 'Pincurchin', displayNumber: '062', dexNumber: '871' },
    { name: 'Snom', displayNumber: '063', dexNumber: '872' },
    { name: 'Frosmoth', displayNumber: '064', dexNumber: '873' },
    { name: 'Stonjourner', displayNumber: '065', dexNumber: '874' },
    { name: 'Eiscue', displayNumber: '066', dexNumber: '875' },
    { name: 'Indeedee', displayNumber: '067', dexNumber: '876' },
    { name: 'Morpeko', displayNumber: '068', dexNumber: '877' },
    { name: 'Cufant', displayNumber: '069', dexNumber: '878' },
    { name: 'Copperajah', displayNumber: '070', dexNumber: '879' },
    { name: 'Dracozolt', displayNumber: '071', dexNumber: '880' },
    { name: 'Arctozolt', displayNumber: '072', dexNumber: '881' },
    { name: 'Dracovish', displayNumber: '073', dexNumber: '882' },
    { name: 'Arctovish', displayNumber: '074', dexNumber: '883' },
    { name: 'Duraludon', displayNumber: '075', dexNumber: '884' },
    { name: 'Dreepy', displayNumber: '076', dexNumber: '885' },
    { name: 'Drakloak', displayNumber: '077', dexNumber: '886' },
    { name: 'Dragapult', displayNumber: '078', dexNumber: '887' },
    { name: 'Zacian', displayNumber: '079', dexNumber: '888' },
    { name: 'Zacian (Crowned Sword)', displayNumber: '080', dexNumber: '888' },
    { name: 'Zamazenta', displayNumber: '081', dexNumber: '889' },
    { name: 'Zamazenta (Crowned Shield)', displayNumber: '082', dexNumber: '889' },
    { name: 'Eternatus', displayNumber: '083', dexNumber: '890' },
    { name: 'Kubfu', displayNumber: '084', dexNumber: '891' },
    { name: 'Urshifu', displayNumber: '085', dexNumber: '892' },
    { name: 'Urshifu (Rapid Strike Style)', displayNumber: '086', dexNumber: '892' },
    { name: 'Zarude', displayNumber: '087', dexNumber: '893' },
    { name: 'Regieleki', displayNumber: '088', dexNumber: '894' },
    { name: 'Regidrago', displayNumber: '089', dexNumber: '895' },
    { name: 'Glastrier', displayNumber: '090', dexNumber: '896' },
    { name: 'Spectrier', displayNumber: '091', dexNumber: '897' },
    { name: 'Calyrex', displayNumber: '092', dexNumber: '898' },
    { name: 'Calyrex (Ice Rider)', displayNumber: '093', dexNumber: '898' },
    { name: 'Calyrex (Shadow Rider)', displayNumber: '094', dexNumber: '898' },
    { name: 'Calyrex (Crowned)', displayNumber: '095', dexNumber: '898' },
    { name: 'Calyrex (Crowned Ice Rider)', displayNumber: '096', dexNumber: '898' },
    { name: 'Calyrex (Crowned Shadow Rider)', displayNumber: '097', dexNumber: '898' },
    { name: 'Toxtricity (Low Key Form)', displayNumber: '098', dexNumber: '849' }, // Alternate Form
    { name: 'Eiscue (Noice Face)', displayNumber: '099', dexNumber: '875' }, // Alternate Form
    { name: 'Indeedee (Female)', displayNumber: '100', dexNumber: '876' }, // Gender Differences
    { name: 'Morpeko (Hangry Mode)', displayNumber: '101', dexNumber: '877' }, // Alternate Form
]

module.exports = SwordShield;